name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential grub-pc-bin grub-common xorriso mtools qemu-system-x86

      - name: Build ISO
        run: make iso

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Yukka-OS.iso
